unique_ids:
  forms:
    TagComponent: K7MN5JHADWPTPUUBUQY6V4WFBL7KTH5Q
    ProjectView: KEDV2KWCNH7RX5J2EFR6RIX2LD7NPIDK
    ProjectView.RowTemplate3.RowTemplate1: 2ZNOR7KMIGHNS4LSN4G6RNQO6KQ2EU2P
    LogoutScreen: DBEENFXBZRMI4HN4QSSWCMIM3DHSY6VL
    ProjectCard: Z7OTTQRBZ7CPO7S2WS7PNKITWK2BWR7Y
    CommentModal: 2VBFCUQGFB7JSL5COEVJFDYWEJTGEAUW
    EditableLink: BLOOJHJMBIA4A243RQOZTB3AUIYQ7SNJ
    ProjectList: YLBII5CUFKR6GN25OT57UOBMWQJ6X577
    Frame: 3MVXI3ZSVZQHTPX6ZQ75A7XYMHCCJ73J
    NewColumnModal: Z6M2GV7MEVLGACD7GFGDDLITG3HYRMQ6
    ProjectView.RowTemplate3: GIO4GK53Q24CP6HLM7LLEGECCF3HOSNW
    CommentModal.ItemTemplate1: HLLH44QHRZLF5Z4T5MGRIR3KO6VS6KJI
  modules:
    StartupModule: SUVIYENX4LVJAUCKKCUCMMGLGMDMS5BC
    GlobalVars: 7NFSON5SFDC5WZRASRIRTBD7LRIIVP5A
  server_modules:
    ServerModule1: FQ5WXBXJPNKJYTBUFW2OEBQJBGSI5BWC
  assets:
    standard-page.html: LBCTKHLMW5EHDWOSJNOCKRXT653VQ7KD
    theme.css: IMECZLPE6PVI2P3YZ4ANI6BFTIALGZ6N
